# Python Training - Intermediate

## I. numpy

[Numpy](https://www.numpy.org) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
# Import convention
import numpy as np

The main object is the **numpy.array**. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. 

### Introduction

In [2]:
# A sample np.array
a = np.arange(15)
print(a)
type(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


numpy.ndarray

Important note: numpy arrays are **homogeneous** (they do not allow for elements of different _data type_, or, in numpy lingo, `dtype`. See rich [documentation on data types](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html)

In [3]:
np.array([1, 'a']) # S21: strings of byte length 21

array(['1', 'a'], dtype='<U11')

numpy has a wide variety of supported data types, and manipulating data types in large datasets can lead to significant improvements in terms of memory use and performance

In [4]:
# Notice the difference with Standard Python when you just invoke the array:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# Standard Python
b = [1,2,3]
b

[1, 2, 3]

In [6]:
# Correct way to create a numpy array:
c = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])
c

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [14]:
# A numpy 2D array with random numbers
np.random.rand(3,2)

array([[0.92651902, 0.84730702],
       [0.6896085 , 0.12824139],
       [0.07630996, 0.04213123]])

In [18]:
# Various attributes
c.shape # returns a tuple

(2, 4)

In [19]:
# Returns the data type of elements inside the array
a.dtype

dtype('int32')

In [21]:
type(a)

numpy.ndarray

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [24]:
np.ones((2,2)) # shape (3,1) implied

array([[1., 1.],
       [1., 1.]])

In [27]:
# Identity matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Indexing

Like in Standard Python, there are several ways to access specific elements or subsets of a numpy array:

Similar to Python lists, numpy arrays can be **sliced**. Since arrays may be multidimensional, you must specify a slice for each dimension of the array

In [28]:
# Slicing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 2 and 3
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [31]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [32]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# We can get slice to get certain rows of n array
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print("")
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)

[[5 6 7 8]] (1, 4)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print("")
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

In [34]:
# Integer Array Indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print("")
print(a[0]) # first row
print("")
print(np.array([a[0, 1], a[2, 1]])) # elements (0,1) and (2,1) of a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]

[ 2 10]


In [35]:
# Boolean Indexing
a = np.arange(12)
print(a > 2)

[False False False  True  True  True  True  True  True  True  True  True]


The following method of boolean indexing is **very important** for pandas Series/DataFrames manipulations, as we will see later: 

In [36]:
# Subset array elements larger than 2
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

### (numpy) Array Math

In [37]:
# array of 10,000 random numbers between 0 and 1
a = np.random.rand(3,2)
a

array([[0.02366769, 0.74743654],
       [0.03477518, 0.1475584 ],
       [0.79185064, 0.38527405]])

In [38]:
# Transpose
a.T

array([[0.02366769, 0.03477518, 0.79185064],
       [0.74743654, 0.1475584 , 0.38527405]])

In [41]:
# Dot Product
b = np.random.rand(2)
a.dot(b)

array([0.21450483, 0.06837528, 0.78468288])

In [47]:
# Simple operations on numpy arrays are element-wise:
a = np.array([9,3,15])
b = np.array([10,6,4])
print(a + b)  # Same as np.add(a,b)
print("")
print(a - b)  # Same as np.subtract(a,b)
print("")
print(a * b)  # Same as np.multiply(a,b)
print("")
print(a / b)  # Same as np.divide(a,b)
print("")
print(a ** b) # Same as np.power(a,b)
print("")
print(np.sqrt(a))

[19  9 19]

[-1 -3 11]

[90 18 60]

[0.9  0.5  3.75]

[-808182895        729      50625]

[3.         1.73205081 3.87298335]


Other operations: `np.min(), np.max(), np.sum()`, etc.

In [48]:
# Statistics
print('Mean: ', np.mean(a))              # Also: np.nanmean() ignores np.nan values within the array
print('Median: ', np.median(a))          # np.nanmedian()
print('Standard Deviation: ', np.std(a)) # np.nanstd(a)
print('90th percentile: ', np.percentile(a, 90))

Mean:  9.0
Median:  9.0
Standard Deviation:  4.898979485566356
90th percentile:  13.799999999999999


Note: `np.nan` is _like_ `None` in Standard Python, but it is of type `float`!

In [49]:
b = np.array([np.nan, 1])

In [50]:
b

array([nan,  1.])

In [51]:
b.dtype

dtype('float64')

There is an abundance of tutorials covering `numpy` in great detail. I will post some links on the Confluence page.

## II. pandas

`pandas` is a Python library written for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. Its name comes from the econometric term _panel data_

Pandas is capable of many tasks including:
- Reading/writing many different data formats
- Selecting subsets of data
- Calculating across rows and down columns
- Finding and filling missing data
- Applying operations to independent groups within the data
- Reshaping data into different forms
- Combing multiple datasets together
- Advanced time-series functionality
- Visualization through matplotlib and seaborn

Its documentation is extremely thorough (2,500+ pages long!) but, in my opinion, it is not very helpful for an audience interested in "real" data analysis: all the data is contrived or randomly generated, and the real power of pandas, multiple operations performed in sequence, is not really outlined there.

In [52]:
# Import convention
import pandas as pd

The main data structures in Pandas are the `Series` and the `DataFrame`

In [57]:
# Load a numpy array into a pd.Series
a = np.random.rand(50)
b = pd.Series(a)
b.head() # Returns the first 5 rows, unless specified otherwise


0    0.614481
1    0.527340
2    0.683276
3    0.100152
4    0.191499
dtype: float64

In [71]:
# Load a Python dictionary into a pd.DataFrame (common variable name: `df`)
data = {
    'number': [1, 10, 100, np.nan, 500],
    'color': ['Red', 'Green', 'Blue', 'Yellow', 'Black'],
    'price': [2.0, 15.50, 3.42, 64.50,np.nan]
}

df = pd.DataFrame(data)
df

number   color  price
0     1.0     Red   2.00
1    10.0   Green  15.50
2   100.0    Blue   3.42
3     NaN  Yellow  64.50
4   500.0   Black    NaN

A `pandas DataFrame` comprises three elements:
    - Index
    - Columns
    - Values

In [72]:
print(df.index) # can be changed with set_index()
print(df.columns) # dtype 'object' is a general string-like data type
type(df.values) # df.values in a numpy array!

RangeIndex(start=0, stop=5, step=1)
Index(['number', 'color', 'price'], dtype='object')


numpy.ndarray

Indexing a pandas DataFrame is an immensely rich topic. Let us just mention that we can manually manipulate the `index` (primary key) of the DataFrame.

In [73]:
df.set_index('color')

number  price
color                
Red        1.0   2.00
Green     10.0  15.50
Blue     100.0   3.42
Yellow     NaN  64.50
Black    500.0    NaN

In [74]:
# Note: `color` can no longer be accessed as a dataframe column
df['color']

0       Red
1     Green
2      Blue
3    Yellow
4     Black
Name: color, dtype: object

Important note: such operations return **copies** of the original DataFrame, without changing the original variable. In order to change that, you either have to reassign to a new variable, or use the `inplace` flag.

In [75]:
df

number   color  price
0     1.0     Red   2.00
1    10.0   Green  15.50
2   100.0    Blue   3.42
3     NaN  Yellow  64.50
4   500.0   Black    NaN

In [76]:
df.set_index('color', inplace=True)
df

number  price
color                
Red        1.0   2.00
Green     10.0  15.50
Blue     100.0   3.42
Yellow     NaN  64.50
Black    500.0    NaN

### Working with missing data

The last row of our dataframe has a `np.nan` (missing) value for `price`. Depending on the specifics of our problem, we might either want to `drop` this row, or impute (`fill`) some value for the missing data:

In [77]:
# Pandas axes: 0 = rows, 1 = columns
df2 = df.dropna(axis=0, how='any') # "Drop all rows where any column has a value of np.nan"
df2

number  price
color               
Red       1.0   2.00
Green    10.0  15.50
Blue    100.0   3.42

In [79]:
# Let us impute the mean of the remaining values
df3 = df.fillna(df['number'].mean()) # Fill all empty "cells" of the DataFrame with the mean value of the "price" column
df3

number   price
color                 
Red       1.00    2.00
Green    10.00   15.50
Blue    100.00    3.42
Yellow  152.75   64.50
Black   500.00  152.75

Pandas Series have numpy-like math operations (`mean(), median(), sum()`, etc.) - Important distinction: Pandas automatically ignores `np.nan` values during these calculations.

In [80]:
# Get some fast counts of NaN rows for `price` column
print(df['price'].isnull().sum())
print(df['price'].notnull().sum())

1
4


As you can see, a great strength of Pandas is its support for practically limitless ** chain operations **. Use carefully - and wisely: it might be easier to perform many operations on one go, but it is harder to debug (if a chain operation fails, you need to figure out which step failed)

In [89]:
# Import a sample dataset from a csv file
import pandas as pd
df = pd.read_csv('d:/Users/PShirbhate/Downloads/Evolent-Python Training/Auto.csv') # Mike, change filepath
df

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0         130    3504          12.0    70   
1    15.0          8         350.0         165    3693          11.5    70   
2    18.0          8         318.0         150    3436          11.0    70   
3    16.0          8         304.0         150    3433          12.0    70   
4    17.0          8         302.0         140    3449          10.5    70   
5    15.0          8         429.0         198    4341          10.0    70   
6    14.0          8         454.0         220    4354           9.0    70   
7    14.0          8         440.0         215    4312           8.5    70   
8    14.0          8         455.0         225    4425          10.0    70   
9    15.0          8         390.0         190    3850           8.5    70   
10   15.0          8         383.0         170    3563          10.0    70   
11   14.0          8         340.0         160    3609           8.0    70   
12   15.0          8         400.0         150    3761           9.5    70   
13   14.0          8         455.0         225    3086          10.0    70   
14   24.0          4         113.0          95    2372          15.0    70   
15   22.0          6         198.0          95    2833          15.5    70   
16   18.0          6         199.0          97    2774          15.5    70   
17   21.0          6         200.0          85    2587          16.0    70   
18   27.0          4          97.0          88    2130          14.5    70   
19   26.0          4          97.0          46    1835          20.5    70   
20   25.0          4         110.0          87    2672          17.5    70   
21   24.0          4         107.0          90    2430          14.5    70   
22   25.0          4         104.0          95    2375          17.5    70   
23   26.0          4         121.0         113    2234          12.5    70   
24   21.0          6         199.0          90    2648          15.0    70   
25   10.0          8         360.0         215    4615          14.0    70   
26   10.0          8         307.0         200    4376          15.0    70   
27   11.0          8         318.0         210    4382          13.5    70   
28    9.0          8         304.0         193    4732          18.5    70   
29   27.0          4          97.0          88    2130          14.5    71   
..    ...        ...           ...         ...     ...           ...   ...   
362  28.0          4         112.0          88    2605          19.6    82   
363  27.0          4         112.0          88    2640          18.6    82   
364  34.0          4         112.0          88    2395          18.0    82   
365  31.0          4         112.0          85    2575          16.2    82   
366  29.0          4         135.0          84    2525          16.0    82   
367  27.0          4         151.0          90    2735          18.0    82   
368  24.0          4         140.0          92    2865          16.4    82   
369  36.0          4         105.0          74    1980          15.3    82   
370  37.0          4          91.0          68    2025          18.2    82   
371  31.0          4          91.0          68    1970          17.6    82   
372  38.0          4         105.0          63    2125          14.7    82   
373  36.0          4          98.0          70    2125          17.3    82   
374  36.0          4         120.0          88    2160          14.5    82   
375  36.0          4         107.0          75    2205          14.5    82   
376  34.0          4         108.0          70    2245          16.9    82   
377  38.0          4          91.0          67    1965          15.0    82   
378  32.0          4          91.0          67    1965          15.7    82   
379  38.0          4          91.0          67    1995          16.2    82   
380  25.0          6         181.0         110    2945          16.4    82   
381  38.0          6        

In [90]:
# df.describe() automatically subsets the numerical columns of the dataframe
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  392.000000  392.000000    392.000000  392.000000   392.000000   
mean    23.445918    5.471939    194.411990  104.469388  2977.584184   
std      7.805007    1.705783    104.644004   38.491160   849.402560   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.000000    4.000000    105.000000   75.000000  2225.250000   
50%     22.750000    4.000000    151.000000   93.500000  2803.500000   
75%     29.000000    8.000000    275.750000  126.000000  3614.750000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration        year      origin  
count    392.000000  392.000000  392.000000  
mean      15.541327   75.979592    1.576531  
std        2.758864    3.683737    0.805518  
min        8.000000   70.000000    1.000000  
25%       13.775000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.025000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

### Chained indexing

##### Example 1

In [98]:
# Subset the dataframe, and then return one column of the subset
df[['mpg', 'cylinders', 'displacement']]['displacement']

0      307.0
1      350.0
2      318.0
3      304.0
4      302.0
5      429.0
6      454.0
7      440.0
8      455.0
9      390.0
10     383.0
11     340.0
12     400.0
13     455.0
14     113.0
15     198.0
16     199.0
17     200.0
18      97.0
19      97.0
20     110.0
21     107.0
22     104.0
23     121.0
24     199.0
25     360.0
26     307.0
27     318.0
28     304.0
29      97.0
       ...  
362    112.0
363    112.0
364    112.0
365    112.0
366    135.0
367    151.0
368    140.0
369    105.0
370     91.0
371     91.0
372    105.0
373     98.0
374    120.0
375    107.0
376    108.0
377     91.0
378     91.0
379     91.0
380    181.0
381    262.0
382    156.0
383    232.0
384    144.0
385    135.0
386    151.0
387    140.0
388     97.0
389    135.0
390    120.0
391    119.0
Name: displacement, Length: 392, dtype: float64

In [101]:
df.set_index('name', inplace=True)

##### Example 2

In [111]:
df.columns
df.head()

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0         130    3504   
buick skylark 320          15.0          8         350.0         165    3693   
plymouth satellite         18.0          8         318.0         150    3436   
amc rebel sst              16.0          8         304.0         150    3433   
ford torino                17.0          8         302.0         140    3449   

                           acceleration  year  origin  
name                                                   
chevrolet chevelle malibu          12.0    70       1  
buick skylark 320                  11.5    70       1  
plymouth satellite                 11.0    70       1  
amc rebel sst                      12.0    70       1  
ford torino                        10.5    70       1

In [113]:
# Location indexing: .loc is primarily label based
df.loc[['chevrolet chevelle malibu']][['year','displacement']]

year  displacement
name                                         
chevrolet chevelle malibu    70         307.0
chevrolet chevelle malibu    71         250.0

##### Example 3

In [108]:
# Location indexing: .iloc is primarily integer position based
df.iloc[2:5].iloc[:, -3:] # Returns rows 2,3,4, and then the last three columns of this subset

acceleration  year  origin
name                                          
plymouth satellite          11.0    70       1
amc rebel sst               12.0    70       1
ford torino                 10.5    70       1

##### Example 4

In [115]:
# Boolean indexing
df[df['acceleration'] == 12][['acceleration', 'mpg']]

acceleration   mpg
name                                         
chevrolet chevelle malibu          12.0  18.0
amc rebel sst                      12.0  16.0
chevrolet impala                   12.0  14.0
ford country squire (sw)           12.0  13.0
pontiac safari (sw)                12.0  13.0
chevrolet impala                   12.0  13.0
pontiac catalina                   12.0  14.0
chevrolet caprice classic          12.0  13.0
ford mustang ii                    12.0  13.0
chevy c10                          12.0  13.0

All these examples are correct pandas code, but it is not _idiomatic_ Let us rewrite them in idiomatic pandas code

In [116]:
# Example 1
df['origin'] # No need to subset a dataframe when the desired end result is a single column

name
chevrolet chevelle malibu            1
buick skylark 320                    1
plymouth satellite                   1
amc rebel sst                        1
ford torino                          1
ford galaxie 500                     1
chevrolet impala                     1
plymouth fury iii                    1
pontiac catalina                     1
amc ambassador dpl                   1
dodge challenger se                  1
plymouth 'cuda 340                   1
chevrolet monte carlo                1
buick estate wagon (sw)              1
toyota corona mark ii                3
plymouth duster                      1
amc hornet                           1
ford maverick                        1
datsun pl510                         3
volkswagen 1131 deluxe sedan         2
peugeot 504                          2
audi 100 ls                          2
saab 99e                             2
bmw 2002                             2
amc gremlin                          1
ford f250           

In [117]:
# Example 3
df.iloc[2:5, -3:]

acceleration  year  origin
name                                          
plymouth satellite          11.0    70       1
amc rebel sst               12.0    70       1
ford torino                 10.5    70       1

#### Value sorting

In [118]:
df.sort_values(by='acceleration', ascending=False) # Remember: this does not alter original df

mpg  cylinders  displacement  horsepower  \
name                                                                           
peugeot 504                        27.2          4         141.0          71   
vw pickup                          44.0          4          97.0          52   
vw dasher (diesel)                 43.4          4          90.0          48   
volkswagen type 3                  23.0          4          97.0          54   
chevrolet chevette                 29.0          4          85.0          52   
oldsmobile cutlass salon brougham  23.9          8         260.0          90   
chevrolet woody                    24.5          4          98.0          60   
peugeot 504                        19.0          4         120.0          88   
mercedes-benz 240d                 30.0          4         146.0          67   
vw rabbit c (diesel)               44.3          4          90.0          48   
volkswagen rabbit custom diesel    43.1          4          90.0          48   
volkswagen super beetle            26.0          4          97.0          46   
mercury monarch                    15.0          6         250.0          72   
buick century                      17.0          6         231.0         110   
toyota corolla 1200                32.0          4          71.0          65   
ford granada ghia                  18.0          6         250.0          78   
ford escort 2h                     29.9          4          98.0          65   
volkswagen 1131 deluxe sedan       26.0          4          97.0          46   
plymouth cricket                   26.0          4          91.0          70   
peugeot 505s turbo diesel          28.1          4         141.0          80   
mercedes benz 300d                 25.4          5         183.0          77   
amc concord                        24.3          4         151.0          90   
audi 5000s (diesel)                36.4          5         121.0          67   
chevrolet cavalier                 28.0          4         112.0          88   
volvo diesel                       30.7          6         145.0          76   
peugeot 504 (sw)                   21.0          4         120.0          87   
ford maverick                      15.0          6         250.0          72   
chevrolet vega                     20.0          4         140.0          90   
fiat 128                           29.0          4          68.0          49   
peugeot 304                        30.0          4          79.0          70   
...                                 ...        ...           ...         ...   
mercury marquis brougham           12.0          8         429.0         198   
pontiac catalina                   16.0          8         400.0         170   
dodge monaco (sw)                  12.0          8         383.0         180   
amc matador                        14.0          8         304.0         150   
buick skylark 320                  15.0          8         350.0         165   
amc ambassador sst                 17.0          8         304.0         150   
pontiac catalina brougham          14.0          8         400.0         175   
datsun 280-zx                      32.7          6         168.0         132   
chevrolet monte carlo landau       15.5          8         350.0         170   
chevrolet citation                 28.8          6         173.0         115   
ford futura                        18.1          8         302.0         139   
pontiac grand prix lj              16.0          8         400.0         180   
oldsmobile omega                   11.0          8         350.0         180   
buick electra 225 custom           12.0          8         455.0         225   
chrysler new yorker brougham       13.0          8         440.0         215   
plymouth satellite                 18.0          8         318.0         150   
amc ambassador brougham            13.0          8         360.0         175   
mercury marquis                    1

### pandas aggregations: the split-apply-combine framework

One of the greatest strengths of pandas is the blazing fast speed it can perform aggregations on large DataFrames. `groupby` comes straight from the SQL world. Such aggregations on pandas are usually understood in three distinct steps:
- The **split** step involves breaking up and grouping a DataFrame depending on the value of the specified key.
- The **apply** step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
- The **combine** step merges the results of these operations into an output.

In [119]:
df.groupby('cylinders')['mpg'].mean()

cylinders
3    20.550000
4    29.283920
5    27.366667
6    19.973494
8    14.963107
Name: mpg, dtype: float64

In [120]:
# Another way to perform the operation above:
df.groupby('cylinders')['mpg'].agg('mean')

cylinders
3    20.550000
4    29.283920
5    27.366667
6    19.973494
8    14.963107
Name: mpg, dtype: float64

In [121]:
# Careful: curly brackets needed when you want multiple columns as output
df.groupby('cylinders')[['mpg', 'weight']].agg({'mean', 'median'})

mpg            weight             
          median       mean median         mean
cylinders                                      
3          20.25  20.550000   2375  2398.500000
4          28.40  29.283920   2230  2305.110553
5          25.40  27.366667   2950  3103.333333
6          19.00  19.973494   3210  3202.120482
8          14.00  14.963107   4140  4114.718447

In [122]:
# You can write short python functions to use as arguments in `apply` or `agg` for customized results
def add_10(s):
    return s + 10

In [129]:
new_df = df.groupby('cylinders')['mpg'].apply(add_10).apply(pd.Series)
# the last `apply` makes new_df look "nicer". like a pd.DataFrame

ValueError: cannot reindex from a duplicate axis

In [ ]:
new_df.columns = ['inflated_score']
new_df

In [ ]:
# Another example of groupby
df.groupby('state')['score'].sum().rename('Total Score').reset_index() # reset_index brings back default indexing

There are three different `apply` instances in the split-apply-combine process:
- aggregate, if we want to get a single value for each group
- filter, if we want to get a subset of the input rows
- transform, if we want to get a new value for each input row

The `groupby` examples we have seen so far were instances of the `aggregate` method:

In [ ]:
# Aggregate
df.groupby('state')['score'].agg('mean')
# same as df.groupby('state')['score'].mean()
# same as df.groupby('state')['score'].aggregate('mean')

In [ ]:
# Filter with lambda function (short function defined on the spot instead of `def...`)
df.groupby('state').filter(lambda x : x['score'].max() > 4)

In [130]:
# Transform - adds new column with same value for each group
df['scaled_mpg'] = df.groupby('cylinders')['mpg'].transform(lambda x : x/x.mean())
df

mpg  cylinders  displacement  horsepower  \
name                                                                           
chevrolet chevelle malibu          18.0          8         307.0         130   
buick skylark 320                  15.0          8         350.0         165   
plymouth satellite                 18.0          8         318.0         150   
amc rebel sst                      16.0          8         304.0         150   
ford torino                        17.0          8         302.0         140   
ford galaxie 500                   15.0          8         429.0         198   
chevrolet impala                   14.0          8         454.0         220   
plymouth fury iii                  14.0          8         440.0         215   
pontiac catalina                   14.0          8         455.0         225   
amc ambassador dpl                 15.0          8         390.0         190   
dodge challenger se                15.0          8         383.0         170   
plymouth 'cuda 340                 14.0          8         340.0         160   
chevrolet monte carlo              15.0          8         400.0         150   
buick estate wagon (sw)            14.0          8         455.0         225   
toyota corona mark ii              24.0          4         113.0          95   
plymouth duster                    22.0          6         198.0          95   
amc hornet                         18.0          6         199.0          97   
ford maverick                      21.0          6         200.0          85   
datsun pl510                       27.0          4          97.0          88   
volkswagen 1131 deluxe sedan       26.0          4          97.0          46   
peugeot 504                        25.0          4         110.0          87   
audi 100 ls                        24.0          4         107.0          90   
saab 99e                           25.0          4         104.0          95   
bmw 2002                           26.0          4         121.0         113   
amc gremlin                        21.0          6         199.0          90   
ford f250                          10.0          8         360.0         215   
chevy c20                          10.0          8         307.0         200   
dodge d200                         11.0          8         318.0         210   
hi 1200d                            9.0          8         304.0         193   
datsun pl510                       27.0          4          97.0          88   
...                                 ...        ...           ...         ...   
chevrolet cavalier                 28.0          4         112.0          88   
chevrolet cavalier wagon           27.0          4         112.0          88   
chevrolet cavalier 2-door          34.0          4         112.0          88   
pontiac j2000 se hatchback         31.0          4         112.0          85   
dodge aries se                     29.0          4         135.0          84   
pontiac phoenix                    27.0          4         151.0          90   
ford fairmont futura               24.0          4         140.0          92   
volkswagen rabbit l                36.0          4         105.0          74   
mazda glc custom l                 37.0          4          91.0          68   
mazda glc custom                   31.0          4          91.0          68   
plymouth horizon miser             38.0          4         105.0          63   
mercury lynx l                     36.0          4          98.0          70   
nissan stanza xe                   36.0          4         120.0          88   
honda accord                       36.0          4         107.0          75   
toyota corolla                     34.0          4         108.0          70   
honda civic                        38.0          4          91.0          67   
honda civic (auto)                 32.0          4          91.0          67   
datsun 310 gx                      3

Pandas is a very powerful library for data manipulation and analysis in Python. Because the operations under the hood are **vectorized**, there is almost **NEVER** a need to iterate over a DataFrame using a `for` loop.

Understanding `pandas` and the underlying structures of `numpy` is a very important "prerequisite" before moving on to `scikit-learn` for predictive analytics. 

## III. scikit-learn

Scikit-learn is a python module for machine learning and is built on top of the numpy, scipy, and matplotlib modules. It comes loaded with lots of features and components. Below are a few of them to help you understand:
 - Supervised learning algorithms
 - Unsupervised learning algorithms
 - Cross-validation
 - Feature extraction
 - Dimensionality reduction
 - Preprocessing
 - Model selection and evaluation
 
It's very well documented online and the official documentation can be found here: http://scikit-learn.org/stable/documentation.html


#### Load the data

In [3]:
# import pandas
import pandas as pd

# import the titanic file 
filepath = "d:/Users/PShirbhate/Downloads/Evolent-Python Training/titanic.csv"
titanic = pd.read_csv(filepath)
titanic.head()

pid pclass  survived     sex   age  sibsp  parch        fare     embarked
0    1    1st         1  female  29.0      0      0  211.337494  Southampton
1    2    1st         1    male   NaN      1      2  151.550003  Southampton
2    3    1st         0  female   2.0      1      2  151.550003  Southampton
3    4    1st         0    male  30.0      1      2  151.550003  Southampton
4    5    1st         0  female  25.0      1      2  151.550003  Southampton

#### Preprocessing

http://scikit-learn.org/stable/modules/preprocessing.html#preprocessing

Account for missing data

In [4]:
# view the dataset to see if there are any missing variables
titanic[titanic['age'].isnull()].shape

(264, 9)

In [5]:
# find exactly where the null values are
titanic.isnull().sum()

pid           0
pclass        0
survived      0
sex           0
age         264
sibsp         0
parch         0
fare          1
embarked      2
dtype: int64

In [6]:
# replace null values in the age column
age_mean = titanic['age'].mean()  # get the mean age used to fill in missing age values
titanic['age'].fillna(age_mean, axis=0, inplace=True)

In [8]:
# drop the remaining missing variables
titanic.dropna(axis=0, inplace=True)

Replace the index with passenger ID

In [9]:
# set the index to the pid variable
titanic.set_index('pid', drop=True, inplace=True)
titanic.head()

pclass  survived     sex        age  sibsp  parch        fare     embarked
pid                                                                           
1      1st         1  female  29.000000      0      0  211.337494  Southampton
2      1st         1    male  29.908852      1      2  151.550003  Southampton
3      1st         0  female   2.000000      1      2  151.550003  Southampton
4      1st         0    male  30.000000      1      2  151.550003  Southampton
5      1st         0  female  25.000000      1      2  151.550003  Southampton

Encode categorical variables

In [10]:
# creating dummy vaiables for categorical variables
titanic_new = pd.get_dummies(titanic)
titanic_new.head(10)

survived        age  sibsp  parch        fare  pclass_1st  pclass_2nd  \
pid                                                                          
1           1  29.000000      0      0  211.337494           1           0   
2           1  29.908852      1      2  151.550003           1           0   
3           0   2.000000      1      2  151.550003           1           0   
4           0  30.000000      1      2  151.550003           1           0   
5           0  25.000000      1      2  151.550003           1           0   
6           1  48.000000      0      0   26.549999           1           0   
7           1  63.000000      1      0   77.958298           1           0   
8           0  39.000000      0      0    0.000000           1           0   
9           1  53.000000      2      0   51.479198           1           0   
10          0  71.000000      0      0   49.504200           1           0   

     pclass_3rd  sex_female  sex_male  embarked_Cherbourg  \
pid                                                         
1             0           1         0                   0   
2             0           0         1                   0   
3             0           1         0                   0   
4             0           0         1                   0   
5             0           1         0                   0   
6             0           0         1                   0   
7             0           1         0                   0   
8             0           0         1                   0   
9             0           1         0                   0   
10            0           0         1                   1   

     embarked_Queenstown  embarked_Southampton  
pid                                             
1                      0                     1  
2                      0                     1  
3                      0                     1  
4                      0                     1  
5                      0                     1  
6                      0                     1  
7                      0                     1  
8                      0                     1  
9                      0                     1  
10                     0                     0

Split the explanatory and repsonse variables

In [11]:
# create an array of the column names
titanic_names = titanic_new.columns.values
titanic_names

array(['survived', 'age', 'sibsp', 'parch', 'fare', 'pclass_1st',
       'pclass_2nd', 'pclass_3rd', 'sex_female', 'sex_male',
       'embarked_Cherbourg', 'embarked_Queenstown',
       'embarked_Southampton'], dtype=object)

In [12]:
# store the resonse and explanatory variables
y = titanic_new['survived']
x = titanic_new[titanic_names[1:]]

In [13]:
x.head()

age  sibsp  parch        fare  pclass_1st  pclass_2nd  pclass_3rd  \
pid                                                                            
1    29.000000      0      0  211.337494           1           0           0   
2    29.908852      1      2  151.550003           1           0           0   
3     2.000000      1      2  151.550003           1           0           0   
4    30.000000      1      2  151.550003           1           0           0   
5    25.000000      1      2  151.550003           1           0           0   

     sex_female  sex_male  embarked_Cherbourg  embarked_Queenstown  \
pid                                                                  
1             1         0                   0                    0   
2             0         1                   0                    0   
3             1         0                   0                    0   
4             0         1                   0                    0   
5             1         0                   0                    0   

     embarked_Southampton  
pid                        
1                       1  
2                       1  
3                       1  
4                       1  
5                       1

In [14]:
y.head()

pid
1    1
2    1
3    0
4    0
5    0
Name: survived, dtype: int64

#### Creating the training and testing dataset

Cross Validation

Learning the parameters of a prediction function and testing it on the same data is a methodological mistake: a model that would just repeat the labels of the samples that it has just seen would have a perfect score but would fail to predict anything useful on yet-unseen data. This situation is called overfitting. To avoid it, it is common practice when performing a (supervised) machine learning experiment to hold out part of the available data as a test set x_test, y_test

In [15]:
# split the dataset into training and testing using train test split
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape )

(1044, 12) (1044,)
(262, 12) (262,)


D:\Users\PShirbhate\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


#### Logistic Regression

Logistic regression, despite its name, is a linear model for classification rather than regression. Logistic regression is also known in the literature as logit regression, maximum-entropy classification (MaxEnt) or the log-linear classifier. In this model, the probabilities describing the possible outcomes of a single trial are modeled using a logistic function.

In [16]:
# import linear model
from sklearn import linear_model

# create logistic regression object
log = linear_model.LogisticRegression()

In [17]:
# train the model using the trainging datasets
model = log.fit(x_train, y_train)

In [20]:
# make the predicitions using the testing set
predictions = model.predict(x_test)
print(predictions)

[0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 1 1 0 1
 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0
 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1
 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0
 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0
 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1
 0 0 0]


In [21]:
# get the accuracy of the model
model.score(x_test, y_test)

0.7900763358778626

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, predictions)
confusion_matrix

array([[134,  23],
       [ 32,  73]], dtype=int64)

In [ ]:
# create the classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

#### K-fold cross validation

Is this model any good? It helps to verify the effectiveness fo the alogrithm using KFold. This will split our data into k buckets, then run the alogirthm using a different bucket as the test set for each iteration.

In [25]:
from sklearn.cross_validation import cross_val_score, cross_val_predict

# perform 10-fold cross validation
scores = cross_val_score(model, x, y, cv = 10)
print(scores)

[0.54961832 0.80916031 0.86259542 0.83206107 0.76335878 0.81679389
 0.70992366 0.65648855 0.65116279 0.75193798]


In [26]:
# get the mean accuracy of all of the models
scores.mean()

0.7403100775193799